### ISSUE TITLE
ระบบธาตุ

### ISSUE THREAD

**Issue by RATCHANON2099** [cherishednoel/cpe103-project-group9#18]
[ระบบแพ้ธาตุ.txt](https://github.com/cherishednoel/cpe103-project-group9/files/9540709/default.txt)
เช็คระบบธาตุหน่อยว่าโอเครไหม อยากให้ปรับอะไรป่าว

**Comment by cherishednoel** [comment]
อยากให้เปลี่ยนระบบธาตุเป็น
- ธาตุมีแค่ 4 ธาตุคือ ดิน น้ำ ลม ไฟ และผู้เล่นสามารถเลือกธาตุได้เมื่อถึงเวลาที่กำหนด(ลดการสุ่มแบบ rng ไม่งั้นคนดวงซวยจะเล่นเท่าไหร่ก็จะไม่ชนะซักที)
- เมื่อเริ่ม 3 เทิร์นแรก ผู้เล่นจะไร้ธาตุ เมื่อครบ 3 เทิร์นแล้วจะเลือกเปลี่ยนธาตุเป็นธาตุที่ต้องการได้ 1 ธาตุ และจะเปลี่ยนธาตุไม่ได้จนกว่าฝั่งศัตรูจะเปลี่ยนเฟส(ศัตรูจะเปลี่ยนเฟสธาตุก่อนค่อยให้ผู้เล่นเลือก)
- บอส/มินิบอสจะเปลี่ยนธาตุตอนเปลี่ยนเฟส(จะเปลี่ยนเฟสตอนตีถึง %เลือด ที่ fix ไว้) โดยการเปลี่ยนธาตุจะเป็น pattern เดิมเสมอ(รอบแรกบอสเปลี่ยนเป็นธาตุไหน รอบต่อไปบอสก็จะเปลี่ยนเป็นธาตุนั้นเสมอ ไม่ว่าจะเล่นกี่ครั้งก็จะเปลี่ยนเป็นธาตุเดิม)
จะได้ลดความ rng ลงแล้วเปลี่ยนเป็นให้ผู้เล่นใช้สมองจำ pattern บอสแทน จะได้ลดโค้ดที่ต้องเขียนเพื่อใช้สุ่มลงด้วย

แล้วก็ไม่ค่อยเข้าใจเรื่องสถานะสุ่มเสี่ยงกับติดเชื้อว่ามันต่างกันยังไง ช่วยอธบิายตรงนี้หน่อยจะได้คอมเม้นถูก

**Comment by cherishednoel** [comment]
เรื่องการเปลี่ยนเฟสบอส ถ้าเป็นมินิบอสจะแค่เปลี่ยนธาตุ(มี 2 เฟส) แต่ถ้าเป็นบอสจะมี gen เกราะตอนเปลี่ยนเฟสแรกกับเปลี่ยนธาตุตอนเปลี่ยนเฟสสอง(มี 3 เฟส)

**Comment by RATCHANON2099** [comment]
> อยากให้เปลี่ยนระบบธาตุเป็น
> 
> * ธาตุมีแค่ 4 ธาตุคือ ดิน น้ำ ลม ไฟ และผู้เล่นสามารถเลือกธาตุได้เมื่อถึงเวลาที่กำหนด(ลดการสุ่มแบบ rng ไม่งั้นคนดวงซวยจะเล่นเท่าไหร่ก็จะไม่ชนะซักที)
> * เมื่อเริ่ม 3 เทิร์นแรก ผู้เล่นจะไร้ธาตุ เมื่อครบ 3 เทิร์นแล้วจะเลือกเปลี่ยนธาตุเป็นธาตุที่ต้องการได้ 1 ธาตุ และจะเปลี่ยนธาตุไม่ได้จนกว่าฝั่งศัตรูจะเปลี่ยนเฟส(ศัตรูจะเปลี่ยนเฟสธาตุก่อนค่อยให้ผู้เล่นเลือก)
> * บอส/มินิบอสจะเปลี่ยนธาตุตอนเปลี่ยนเฟส(จะเปลี่ยนเฟสตอนตีถึง %เลือด ที่ fix ไว้) โดยการเปลี่ยนธาตุจะเป็น pattern เดิมเสมอ(รอบแรกบอสเปลี่ยนเป็นธาตุไหน รอบต่อไปบอสก็จะเปลี่ยนเป็นธาตุนั้นเสมอ ไม่ว่าจะเล่นกี่ครั้งก็จะเปลี่ยนเป็นธาตุเดิม)
> 
> จะได้ลดความ rng ลงแล้วเปลี่ยนเป็นให้ผู้เล่นใช้สมองจำ pattern บอสแทน จะได้ลดโค้ดที่ต้องเขียนเพื่อใช้สุ่มลงด้วย
> 
> แล้วก็ไม่ค่อยเข้าใจเรื่องสถานะสุ่มเสี่ยงกับติดเชื้อว่ามันต่างกันยังไง ช่วยอธิบายตรงนี้หน่อยจะได้คอมเม้นถูก

_สถานะ_
-บัฟ-
-ป้องกันการติดเชื้อ ป้องกันการติดดีบัฟ "ติดเชื้อ" และ "สุ่มเสี่ยง" 60 เปอร์เซน
-ล้างบัฟ ลบล้าง ดีบัฟ "สุ่มเสี่ยง" และ "ติดเชื้อ"
-แพร่เชื้อ ทำให้ผู้โจมตีติดสถานะ "ติดเชื้อ" (หากมีบัฟป้องจะคิดอัตราติดเชื้อตามบัฟป้องกัน "60 เปอร์เซน")

-ดีบัฟ-
-ติดเชื้อ โดนดาเมจแรงขึ้นและลดเลือดทุกๆครั้งที่ถึงเทิร์น (จะไม่มีวันหายไปหากไม่ได้รับการรักษา)
-สุ่มเสี่ยง หลังจบเทิร์นผู้สุ่มเสี่ยงมีโอกาส 50 เปอร์เซน ที่จะติดเชื้อ สามารถใช้สกิลล้างบัฟได้

**Comment by cherishednoel** [comment]
> > อยากให้เปลี่ยนระบบธาตุเป็น
> > 
> > * ธาตุมีแค่ 4 ธาตุคือ ดิน น้ำ ลม ไฟ และผู้เล่นสามารถเลือกธาตุได้เมื่อถึงเวลาที่กำหนด(ลดการสุ่มแบบ rng ไม่งั้นคนดวงซวยจะเล่นเท่าไหร่ก็จะไม่ชนะซักที)
> > * เมื่อเริ่ม 3 เทิร์นแรก ผู้เล่นจะไร้ธาตุ เมื่อครบ 3 เทิร์นแล้วจะเลือกเปลี่ยนธาตุเป็นธาตุที่ต้องการได้ 1 ธาตุ และจะเปลี่ยนธาตุไม่ได้จนกว่าฝั่งศัตรูจะเปลี่ยนเฟส(ศัตรูจะเปลี่ยนเฟสธาตุก่อนค่อยให้ผู้เล่นเลือก)
> > * บอส/มินิบอสจะเปลี่ยนธาตุตอนเปลี่ยนเฟส(จะเปลี่ยนเฟสตอนตีถึง %เลือด ที่ fix ไว้) โดยการเปลี่ยนธาตุจะเป็น pattern เดิมเสมอ(รอบแรกบอสเปลี่ยนเป็นธาตุไหน รอบต่อไปบอสก็จะเปลี่ยนเป็นธาตุนั้นเสมอ ไม่ว่าจะเล่นกี่ครั้งก็จะเปลี่ยนเป็นธาตุเดิม)
> > 
> > จะได้ลดความ rng ลงแล้วเปลี่ยนเป็นให้ผู้เล่นใช้สมองจำ pattern บอสแทน จะได้ลดโค้ดที่ต้องเขียนเพื่อใช้สุ่มลงด้วย
> > แล้วก็ไม่ค่อยเข้าใจเรื่องสถานะสุ่มเสี่ยงกับติดเชื้อว่ามันต่างกันยังไง ช่วยอธิบายตรงนี้หน่อยจะได้คอมเม้นถูก
> 
> _สถานะ_ -บัฟ- -ป้องกันการติดเชื้อ ป้องกันการติดดีบัฟ "ติดเชื้อ" และ "สุ่มเสี่ยง" 60 เปอร์เซน -ล้างบัฟ ลบล้าง ดีบัฟ "สุ่มเสี่ยง" และ "ติดเชื้อ" -แพร่เชื้อ ทำให้ผู้โจมตีติดสถานะ "ติดเชื้อ" (หากมีบัฟป้องจะคิดอัตราติดเชื้อตามบัฟป้องกันที่ป้องกันการติดดีบัฟ "60 เปอร์เซน")
> 
> -ดีบัฟ- -ติดเชื้อ โดนดาเมจแรงขึ้นและลดเลือดทุกๆครั้งที่ถึงเทิร์น (จะไม่มีวันหายไปหากไม่ได้รับการรักษา) -สุ่มเสี่ยง หลังจบเทิร์นผู้สุ่มเสี่ยงมีโอกาส 50 เปอร์เซน ที่จะติดเชื้อ สามารถใช้สกิลล้างบัฟได้

สถานะอันอื่นโอเคละ แต่ตรงสถานะดีบัฟ เราเอาสถานะดีบัฟเป็นเหลือแค่ติดเชื้อกับไม่ติดเชื้อดีกว่า เดี๋ยวโค้ดจะทำยากเกิน เพราะมันต้องสุ่มโอกาสที่จะเปลี่ยนจากสุ่มเสี่ยงเป็นติดเชื้ออีก
