### ISSUE TITLE
เจอ Bugs 

### ISSUE THREAD

**Issue by RATCHANON2099** [cherishednoel/cpe103-project-group9#33]
![image](https://user-images.githubusercontent.com/110969818/189955738-f55df995-70eb-4ef6-b9c4-5fbd8af0b129.png)

![image](https://user-images.githubusercontent.com/110969818/189955773-bf6a9979-4170-4146-b814-94b3a7ed1b0f.png)

เจอ Bugs ตอนกดเริ่มเกมระหว่าง 2 ฉากนี้

**Comment by littleMxrch** [comment]
โอเค เดี๋ยวเราไปแก้มาให้
