### ISSUE TITLE
รายงานความคืบหน้าโครงงาน ประจำวันอาทิตย์ 18/9/2022

### ISSUE THREAD

**Issue by cherishednoel** [cherishednoel/cpe103-project-group9#35]
รายงานความคืบหน้าตาม to-do list นี้
<img width="553" alt="ภาพถ่ายหน้าจอ 2565-09-16 เวลา 21 26 09" src="https://user-images.githubusercontent.com/110964402/190911903-edf092db-50c9-411c-bc7f-b82999b6c38c.png">

**Comment by RATCHANON2099** [comment]
![image](https://user-images.githubusercontent.com/110969818/190913762-4c4b28e6-6475-4923-9fa6-50cd4fd0cb00.png)
เริ่มหา sound แล้วครับ

**Comment by littleMxrch** [comment]
กำลังทำเนื้อเรื่องช่วงท้ายๆกับหาข้อมูลโควิครับ

**Comment by littleMxrch** [comment]
เหลือเอาเนื้อเรื่องที่เหลือใส่ในGame Playแล้วก็ใส่sound Effect
