### ISSUE TITLE
กดอันติ แล้วกดสกิลพิเศษได้พร้อมกันในเทิร์นเดียว

### ISSUE THREAD

**Issue by RATCHANON2099** [cherishednoel/cpe103-project-group9#44]
![image](https://user-images.githubusercontent.com/110969818/191433652-7562acc7-6538-48a0-abdb-61ba2997c442.png)
กดสกิลพิเศษแล้วกดสกิลอื่นไม่ได้แล้ว
แต่กดสกิลอันติ แล้วกดสกิลพิเศษได้พร้อมกันในเทิร์นเดียว

**Comment by Ta0Huu** [comment]
แก้บัคแร้ววครับพรี่
