### ISSUE TITLE
ทำ Monster Design

### ISSUE THREAD

**Issue by cherishednoel** [cherishednoel/cpe103-project-group9#5]
- [x] ดีไซน์กีกี้ 1 2 3
- [x] ดีไซน์มินิบอส
- [x] ดีไซน์บอส

**Comment by Ta0Huu** [comment]
![toppng com-slime-slime-1751x1146](https://user-images.githubusercontent.com/99076360/188668712-aeeeea4c-ab2b-4cb8-89be-5f5d275c3434.png)

**Comment by cherishednoel** [comment]
> ![toppng com-slime-slime-1751x1146](https://user-images.githubusercontent.com/99076360/188668712-aeeeea4c-ab2b-4cb8-89be-5f5d275c3434.png)
> 
> 

อันนี้น่ารัก🥺

**Comment by littleMxrch** [comment]
![image](https://user-images.githubusercontent.com/110961271/188818644-311c223b-3195-43e7-926d-06f1e22ab22a.jpeg)
อันนี้ก็น่ารักนะ
