### ISSUE TITLE
ทำ Skill Design

### ISSUE THREAD

**Issue by cherishednoel** [cherishednoel/cpe103-project-group9#6]
- [x] สกิลน้องซาลาเปา
- [x] สกิลบอส
- [x] สกิลมินิบอส
- [x] สกิลกีกี้

**Comment by cherishednoel** [comment]
ทำเสร็จแล้วอย่าลืมเอาให้คนโค้ดดูนะ @RATCHANON2099

**Comment by RATCHANON2099** [comment]
> ทำเสร็จแล้วอย่าลืมเอาให้คนโค้ดดูนะ @RATCHANON2099

เรียบร้อยแล้วครับ
