### ISSUE TITLE
Project Resource

### ISSUE THREAD

**Issue by cherishednoel** [cherishednoel/cpe103-project-group9#7]
ใช้เก็บ references, project pics, etc.
OneDrive : https://o365cmu-my.sharepoint.com/:f:/g/personal/panida_suthapakti_cmu_ac_th/Ep-jqi_1UGhMkqTEw0BPIVQBR-d9MlYQaNOUOwSOBfOa1w?e=yEq84U

**Comment by Ta0Huu** [comment]
ของฟรี ของดีย์ มีที่นี่ 
https://itch.io/game-assets/free/tag-animation
